// UI Actions
export const POPUP_CLOSE = 'POPUP_CLOSE';
export const POPUP_OPEN = 'POPUP_OPEN';

// Reddit Actions
export const FETCH_REDDIT = 'FETCH_REDDIT';
export const REDDIT_SUCCESS = 'REDDIT_SUCCESS';
export const REDDIT_FAILURE = 'REDDIT_FAILURE';
export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT';
export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT';

export const UPDATE_DATA_STATE = 'UPDATE_DATA_STATE';

export const FETCH_FLICKR = 'FETCH_FLICKR';
export const FLICKR_SUCCESS = 'FLICKR_SUCCESS';
export const FLICKR_FAILURE = 'FLICKR_FAILURE';

export const SHOW_LOCK = 'SHOW_LOCK';
export const LOCK_SUCCESS = 'LOCK_SUCCESS';
export const LOCK_ERROR = 'LOCK_ERROR';


export const GLOBE_INSTANTIATED = 'GLOBE_INSTANTIATED';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


